/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hdi;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashu
 */
public class ChngPassword extends javax.swing.JFrame {

    /**
     * Creates new form ChngPassword
     */
    public ChngPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        np = new javax.swing.JPasswordField();
        cp = new javax.swing.JPasswordField();
        cnp = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        hv = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 400, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Change Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 0, -1, 40));

        jLabel15.setText("Confirm Password :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 125, -1, -1));

        jLabel14.setText("Enter Your New Password :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 96, -1, -1));

        jLabel4.setText("Enter Your Current Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, -1, -1));
        getContentPane().add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 93, 196, -1));
        getContentPane().add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 64, 196, -1));
        getContentPane().add(cnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 122, 196, -1));

        jButton4.setText("<<BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 176, 82, -1));

        jButton5.setText("PROCEED");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 176, 142, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 159, 400, 10));
        getContentPane().add(hv, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 208, -1, -1));

        setSize(new java.awt.Dimension(418, 255));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
        hv.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String old_password = new String(cp.getPassword());

        if(old_password.equals("")){
            JOptionPane.showMessageDialog(null,"PLEASE ENTER PASSWORDS!");
        }else{
            String npass = new String(np.getPassword());
            String cnpass =new String(cnp.getPassword());
            if(!npass.equals(cnpass)){
                JOptionPane.showMessageDialog(null,"THE ENTERED NEW PASSWORDS DO NOT MATCH!!");
            }
            try{
                Connection con = Connect.getConnection();
                Statement stmt = con.createStatement();
                String qry="Select password FROM password ;";
                ResultSet rs = stmt.executeQuery(qry);
                while(rs.next()){
                    hv.setText(rs.getString("password"));
                    }
                rs.close();
                stmt.close();
                con.close();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,"THE PASSWORD IS NOT CHANGED! PLEASE TRY AGAIN");
            }
            
            String pswd=hv.getText();

            if(old_password.equals(pswd)){
                
                try{
                    Connection con = Connect.getConnection();
                    Statement stt = con.createStatement();
                    String qury=("UPDATE password set password ='"+ cnpass +"';");
                    stt.executeUpdate(qury);
                    JOptionPane.showMessageDialog(null,"PASSWORD CHANGED...");
                    cp.setText("");
                    np.setText("");
                    cnp.setText("");
                    stt.close();
                    con.close();
                }catch(HeadlessException | SQLException h){
                    JOptionPane.showMessageDialog(null,"Error in changing PASSWORD");
                    cp.setText("");
                    np.setText("");
                    cnp.setText("");
                }
                
            }else{
                JOptionPane.showMessageDialog(null,"PASSWORDS DO NOT MATCH");
                cp.setText("");
                np.setText("");
                cnp.setText("");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChngPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChngPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChngPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChngPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChngPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField cnp;
    private javax.swing.JPasswordField cp;
    private javax.swing.JLabel hv;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField np;
    // End of variables declaration//GEN-END:variables
}
